# Generated by Django 4.2.8 on 2026-01-27 21:47

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(default=api.models.generate_user_id, max_length=100, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('lista_amigos_ids', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('distancia_km', models.FloatField()),
                ('litros_consumidos', models.FloatField()),
                ('coche_usado', models.CharField(max_length=200)),
                ('timestamp', models.BigIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='api.usuario')),
            ],
            options={
                'db_table': 'viajes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('city_kmpl', models.CharField(default='0.0', max_length=20)),
                ('highway_kmpl', models.CharField(default='0.0', max_length=20)),
                ('avg_kmpl', models.CharField(default='0.0', max_length=20)),
                ('capacidad_deposito', models.IntegerField(default=-1)),
                ('capacidad_actual', models.IntegerField(default=-1)),
                ('veces_usado', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coches', to='api.usuario')),
            ],
            options={
                'db_table': 'coches',
            },
        ),
    ]
